Nas 107708
freenas/webui pull request #4771
Opened 2020-10-16 11:16 UTC by dszidi

Add support for ES24f and ES102
Fix orientation for E60 and ES60 (They should be ordered from top to bottom not left to right)

2020-10-16 15:02 UTC, darkfiberiru requested changes
Should be s/ES24f/ES24F/g every where. Original ticket had type that Andrew Nguyen Product PM informed me of.

2020-10-16 15:02 UTC, darkfiberiru commented on src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
> +import { ES24f } from 'app/core/classes/hardware/es24f';
Should be ES24F

2020-10-19 15:59 UTC, dkmullen approved these changes
Looks good - there is one active console log on line 496 in enclosure-disks.compoment

2020-10-20 13:09 UTC, dkmullen commented
@darkfiberiru Could you look at this PR again and see if your requested changes are done?

2020-10-20 18:39 UTC, darkfiberiru approved these changes
My suggestion look fixed. Good to go. Haven't tested on real system yet but can once we have a nightly

2020-10-20 18:59 UTC, merged