Properly show if there are no installed apps in UI
freenas/webui pull request #5061
Opened 2021-01-19 20:27 UTC by AlexKarpov98

2021-01-20 07:31 UTC, sonicaj reviewed
Do you think the text is perhaps too small ?
![Screenshot 2021-01-20 at 12 30 43 PM](https://user-images.githubusercontent.com/17968138/105141739-7465b800-5b1b-11eb-8942-6fe2b6b6e941.png)

2021-01-20 07:33 UTC, sonicaj commented
I do like @dszidi suggestion in the ticket, not sure if UI would like to do that - but just my opinion :p

2021-01-21 21:33 UTC, AlexKarpov98 commented
Implemented Empty State component and applied it on Apps section

2021-01-22 16:41 UTC, dszidi commented on src/app/pages/applications/chart-releases/chart-releases.component.ts
>      title: helptext.message.loading,
Lets add a message too.

"Applications you install will automatically appear here. Click below and browse the TrueNAS catalog to get started."

2021-01-22 17:12 UTC, dszidi requested changes
Great start to the empty state component! Couple of things need to be tweaked though. The magnify icon is meant to be shown in scenarios where a search has returned no results, so it's not really appropriate here. On this page the "format-list-text" icon would be a better choice IMO. Perhaps better property names could also be used. Let's try these changes:

- Rename `user_cleared`  to  `no_page_data`
- Rename `no_results` to `no_search_results`
- Set the type to `no_page_data` for this page
- Add this message "Applications you install will automatically appear here. Click below and browse the TrueNAS catalog to get started." 

The other thing is that the loader shows the button and the message too. The loader scenario should only show the logo. Also a delay might be good here since the empty component comes up rather quickly.

2021-01-22 21:35 UTC, AlexKarpov98 commented
Fixed

2021-01-22 21:37 UTC, dszidi commented
The message requested in the previous comment was supposed to be the EmptyConfig.message value. It should look like this...

![image](https://user-images.githubusercontent.com/29865743/105550949-08788080-5cd0-11eb-9b04-075d2573c66a.png)

2021-01-22 21:57 UTC, dszidi approved these changes
LGTM

2021-01-26 14:26 UTC, merged