Add "show_if" to all types / NAS-109244
freenas/webui pull request #5108
Opened 2021-02-04 15:29 UTC by AlexKarpov98

2021-02-05 14:36 UTC, sonicaj approved these changes

2021-02-05 14:36 UTC, sonicaj commented on src/app/pages/applications/forms/chart-form.component.ts
> +          fieldConfig['relation'] = this.createRelations(schemaConfig.schema.show_if, parentName);;
Extra `;` ?

2021-02-05 14:37 UTC, sonicaj requested changes
Actually no, it is not working as intended

2021-02-05 15:28 UTC, AlexKarpov98 commented on src/app/pages/applications/forms/chart-form.component.ts
> +          fieldConfig['relation'] = this.createRelations(schemaConfig.schema.show_if, parentName);;
Sure

2021-02-05 15:28 UTC, AlexKarpov98 commented
It should work, please check again.

2021-02-05 15:35 UTC, sonicaj approved these changes
Yup it was browser cache. Thanks

2021-02-08 22:17 UTC, dszidi approved these changes
LGTM

2021-02-08 22:18 UTC, merged